// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YjH9y_PzDApbvOkbd3mt1edlRiUsCCs',
    appId: '1:50537670515:web:7aae3b5754a18675c20706',
    messagingSenderId: '50537670515',
    projectId: 'odontobd-ec688',
    authDomain: 'odontobd-ec688.firebaseapp.com',
    storageBucket: 'odontobd-ec688.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBUDTEigHPrz8dV6IVv44BqvLJwC2WM8',
    appId: '1:50537670515:android:f9d5b768d08e4008c20706',
    messagingSenderId: '50537670515',
    projectId: 'odontobd-ec688',
    storageBucket: 'odontobd-ec688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6DiEBLRMLZYNohGZjf1WJMRBpt0fafr4',
    appId: '1:50537670515:ios:3d10e288bcc1659ac20706',
    messagingSenderId: '50537670515',
    projectId: 'odontobd-ec688',
    storageBucket: 'odontobd-ec688.firebasestorage.app',
    iosBundleId: 'com.example.odontouf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6DiEBLRMLZYNohGZjf1WJMRBpt0fafr4',
    appId: '1:50537670515:ios:3d10e288bcc1659ac20706',
    messagingSenderId: '50537670515',
    projectId: 'odontobd-ec688',
    storageBucket: 'odontobd-ec688.firebasestorage.app',
    iosBundleId: 'com.example.odontouf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YjH9y_PzDApbvOkbd3mt1edlRiUsCCs',
    appId: '1:50537670515:web:981e557dd9b3039dc20706',
    messagingSenderId: '50537670515',
    projectId: 'odontobd-ec688',
    authDomain: 'odontobd-ec688.firebaseapp.com',
    storageBucket: 'odontobd-ec688.firebasestorage.app',
  );
}
